#!/bin/sh
# Verschiedene Hallo Welts
echo "Hallo,	Welt!"
echo "Hallo, Welt!"
echo "Hallo * Welt!"
echo Hallo * Welt
echo Hallo		Welt
echo "Hallo" Welt
echo Hallo "	"	Welt
echo "Hallo "*" Welt!"
echo 'Hallo' Welt!
echo `Hallo` Welt!
